<template>
  <div class="dropzone-wrapper p-1 p-md-2 p-lg-3">
    <vue-dropzone
        :class="{ disabled: _disabled }"
        :style="_style"
        ref="dropzone"
        :id="_id"
        :options="dropOptions"
        :duplicateCheck="_duplicateCheck"
        @vdropzone-success="DZuploadSuccess"
        @vdropzone-canceled="$emit('upload-canceled', $event)"
        @vdropzone-removed-file="deleteFile"
        @vdropzone-max-files-reached="$emit('max-files-reached', $event)"
        @vdropzone-duplicate-file="$emit('duplicate-file', $event)"
        @vdropzone-complete="$emit('upload-complete', $event)"
    >
    </vue-dropzone>

    <div class="mt-2 mt-lg-3" v-if="!_disabled">
      <button class="btn btn-info" type="button" @click="DZselectFiles">
        <i class="fa fa-folder-open mr-2"></i>{{ i18n.choseFiles }}
      </button>
      <button class="btn btn-info" type="button" @click="DZprocessQueue">
        <i class="fa fa-cloud-upload mr-2"></i>{{ i18n.uploadFiles }}
      </button>
      <button
          v-if="_dzOptions.maxFiles === 1"
          @click="DZremoveAllFiles"
          class="btn btn-warning"
          type="button"
      >
        <i :class="['fa fa-trash', i18n.removeFiles ? 'mr-2' : '']"></i
        >{{ i18n.removeFiles }}
      </button>
      <slot name="additional-buttons"></slot>
    </div>

    <input
        :name="_name"
        :value="guid"
        :id="_input_id"
        hidden
        class="form-control"
    />
    <div class="invalid-feedback"></div>
  </div>
</template>

<script>
import vueDropzone from 'vue2-dropzone-vue3';
import dzDefaultOptions from './dzDefaultOptions';
// import { showNotify } from '@/functions';
import './style.css';

export default {
  name: 'VdDropzone',
  props: {
    _id: {
      type: String,
      required: true,
    },
    _name: {
      type: String,
      required: true,
    },
    _uploadUrl: {
      type: String,
      required: true,
    },
    _initialValue: {
      type: Array,
      default: () => [],
    },
    _dzOptions: {
      type: Object,
    },
    _duplicateCheck: {
      type: Boolean,
      default: false,
    },
    _disabled: {
      type: Boolean,
      default: false,
    },
    _i18n: {
      type: Object,
      default: () => ({}),
    },
    _style: [String, Object],
    _moduleId: {
      type: String,
      default: function () {
        return window ? window.location.pathname : '';
      },
    },
    _input_id: {
      type: String,
      default: function () {
        return 'autogenerated-file-id-' + Math.random();
      },
    },
  },
  data() {
    return {
      guid: [],
    };
  },
  methods: {
    DZprocessQueue() {
      this.$refs.dropzone.processQueue();
    },
    DZuploadSuccess(file) {
      let guid;
      let _file = {};
      const chunks = file.upload.chunks;

      for (const chunk of chunks.reverse()) {
        //guid скорее всего будет одним из последних
        // console.dir(chunk)
        const json = JSON.parse(chunk.response);
        guid = json.guid;
        if (guid) {
          _file = {
            url: file.dataURL,
            guid: guid,
            name: file.name,
            size: file.size,
            type: file.type,
          };
          break;
        }
      }
      file.guid = guid;
      this.guid.push(guid);
      this.$emit('file-added', { guid: guid, file: _file });
    },
    DZselectFiles() {
      this.$refs.dropzone.$el.click();
    },
    DZremoveAllFiles() {
      this.$refs.dropzone.removeAllFiles();
    },
    deleteFile(file) {
      if (!file || !file.guid) return;

      if (this._disabled) {
        this.addFile(file, true);
        return;
      }

      const index = this.guid.findIndex((i) => i === file.guid);
      if (~index) {
        this.guid.splice(index, 1);
        this.$emit('delete', file.guid);
      }
    },
    addFile(file, emit) {
      const { guid, url, thumb, index } = file;
      this.$refs.dropzone.manuallyAddFile(file, thumb || url);
      this.guid.push(guid);
      if (emit) {
        this.$emit('file-added', { guid, index, file });
      }
    },
    cancelUpload(file) {
      this.$refs.dropzone.dropzone.cancelUpload(file);
      //console.log('chunkError: ', file.chunkError, file)
      //const el = file.previewElement.getElementsByClassName('dz-error-message')[0].getElementsByTagName('span')[0].innerText = ''
    },

    showGallery(fileObj) {
      const imgs = [];
      let index;
      const files = this.$refs.dropzone.dropzone.files;

      for (const [idx, file] of files.entries()) {
        const url = file.url || file.dataURL;
        if (file === fileObj) {
          index = idx;
        }
        imgs.push(url);
      }

      const rootLightbox = window.top.vueApp.$refs['vd-lightbox-root'];
      rootLightbox.showGallery({ imgs, index });
    },
  },
  created() {
    const i18n = {
      editFile: 'Редагувати',
      choseFiles: 'Вибрати...',
      uploadFiles: 'Відвантажити',
      removeFiles: 'Видалити',
    };

    this.i18n = {
      ...i18n,
      ...this._i18n,
    };

    const vm = this;
    this.dropOptions = {
      url: vm._uploadUrl,
      ...dzDefaultOptions,
      ...vm._dzOptions,
      init: function () {
        this.on('sending', function (file, xhr, formData) {
          formData.append('createdDate', file.lastModified);
          formData.append('fileName', file.name);
          formData.append('type', file.type);
          formData.append('moduleId', vm._moduleId);

          /*xhr.onreadystatechange = function () {
            if(xhr.readyState === XMLHttpRequest.DONE && xhr.status !== 200) {
              file.chunkError = true;
              vm.cancelUpload(file)
            }
            if(xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
              try {
                const json = JSON.parse(xhr.response);
                if (json.error) {
                  file.chunkError = true;
                  vm.cancelUpload(file)
                }
              } catch (error) {
                file.chunkError = true;
                vm.cancelUpload(file)
              }
            }
          }*/
        });
        this.on('addedfile', function (file) {
          if (/(image)/.test(file.type)) {
            const btn = document.createElement('button');
            btn.className = 'btn dz-lightbox-btn';
            btn.innerHTML = '<i class="ti-zoom-in"></i>';
            btn.addEventListener('click', function (e) {
              e.preventDefault();
              e.stopPropagation();
              vm.showGallery(file);
            });
            file.previewElement.appendChild(btn);
          }
        });
      },
    };
  },
  mounted() {
    // add allready uploaded file to thumbs
    for (const file of this._initialValue) {
      this.addFile(file);
    }
    if (this._disabled) {
      this.$refs.dropzone.disable();
    }

    const valid = document.querySelectorAll('#' + this._id).length < 2;
    // if (!valid) {
    //   showNotify('Dropzone id must be unique', 'danger');
    // }
  },
  beforeDestroy() {
    this.$emit('before-destroy');
  },
  destroyed() {
    this.$emit('destroyed');
  },
  watch: {
    guid: function (val) {
      this.$emit('change', val);
    },
  },
  components: {
    vueDropzone,
  },
};
</script>

<style>
.dropzone-wrapper {
  border-radius: 5px;
  border: 1px solid #e0e0e0;
}
.vue-dropzone {
  border: 1px dashed #bdbdbd;
  border-radius: 4px;
  padding: 5px;
}
.vue-dropzone:hover {
  background-color: #f5f5f5;
}
.dropzone .dz-preview {
  width: 200px;
  height: 200px;
}
.vue-dropzone.dropzone > .dz-preview .dz-image {
  border-radius: 0;
  width: 100%;
  height: 0;
  padding-bottom: 100%;
}
.vue-dropzone.dropzone .dz-preview .dz-image img {
  width: auto !important;
  height: auto !important;
  max-width: 100%;
  max-height: 100%;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  margin: auto;
}

@media (max-width: 1024) {
  .dropzone .dz-preview {
    width: 150px;
    height: 150px;
    margin: 0.25rem;
  }
}
.dropzone .dz-preview .dz-image img {
  width: 100% !important;
  height: 100% !important;
}
.dropzone .dz-message {
  text-align: center;
  margin: 0;
  color: #9e9e9e;
  font-size: 1.6em;
  padding: 85px 10px;
}
.dropzone .dz-error-mark svg path {
  fill: #f44336;
}
.dropzone .dz-success-mark svg path {
  fill: #4caf50;
}
.vue-dropzone.dropzone .dz-preview .dz-error-message {
  top: 100%;
  border-radius: 0;
}
.vue-dropzone > .dz-preview .dz-remove {
  margin: 0;
  left: 1rem;
  right: 1rem;
  text-decoration: none !important;
}

.dropzone.disabled .dz-remove {
  display: none;
}

.dropzone .dz-preview .dz-lightbox-btn {
  cursor: pointer;
  position: absolute;
  top: 1rem;
  right: 1rem;
  z-index: 20;
  opacity: 0;
  border: 1px #fff solid;
  color: #fff;
  padding-top: 0.5rem;
}
.dropzone .dz-preview .dz-lightbox-btn i {
  cursor: pointer;
}
.vue-dropzone > .dz-preview:hover .dz-lightbox-btn {
  opacity: 1;
}
</style>
